### ISSUE TITLE
runtimeerror

### ISSUE THREAD

**Issue by Polaris231** [hyeonseobnam/sagnet#1]
![image](https://user-images.githubusercontent.com/58073043/113855119-431f8e80-97d2-11eb-8146-c9a2de8125da.png)

**Comment by Polaris231** [comment]
This issue has been resolved. This error will be reported if the PyTorch version is 1.6

**Comment by Polaris231** [comment]
This issue has been resolved. This error will be reported if the PyTorch version is 1.6

**Comment by GA-17a** [comment]
Hi @Polaris231,
The error also was reported when my PyTorch version is 1.8.1. How did you solve this issue？

**Comment by GA-17a** [comment]
Hi @Polaris231 ,
How did you solve this error? I met the same error when my PyTorch version is 1.8.1.

**Comment by Polaris231** [comment]
well,when i changed the pytorch version to 1.3, and there is no problem happend.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月28日(星期一) 中午12:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hyeonseobnam/sagnet] runtimeerror (#1)





 
Hi @Polaris231 ,
 How did you solve this error? I met the same error when my PyTorch version is 1.8.1.

**Comment by sherlockers** [comment]
@Polaris231 Can you share me the processed dataset which sagnet uses？
