### ISSUE TITLE
Having an inplace operation when using the argument '--sagnet'

### ISSUE THREAD

**Issue by C-SunRay** [hyeonseobnam/sagnet#3]
I am very confused since I have not seen the inplace operation in the code, and i  have changed all the relu(True) to relu()
It would mean a lot if anybody could help me there.
![image](https://user-images.githubusercontent.com/57622222/145077779-012b9234-933a-40e7-8546-9463699ad9d2.png)

**Comment by mercier111** [comment]
I have the same error message. hoping for help

**Comment by whuyyc** [comment]
I have the same error message. hoping for help

**Comment by whuyyc** [comment]
@hyeonseobnam

**Comment by sherlockers** [comment]
Hi!Can you share me the processed dataset?

**Comment by sherlockers** [comment]
> I have the same error message. hoping for help
Hi!Can you share me the processed dataset?

**Comment by whuyyc** [comment]
Guys, the error disappeared after reducing the version of Pytorch(<= 1.4). @sherlockers @mercier111 @C-SunRay

**Comment by sherlockers** [comment]
> Guys, the error disappeared after reducing the version of Pytorch(<= 1.4). @sherlockers @mercier111 @C-SunRay

Hi!Can you share me the processed dataset?

**Comment by whuyyc** [comment]
> > Guys, the error disappeared after reducing the version of Pytorch(<= 1.4). @sherlockers @mercier111 @C-SunRay
> 
> Hi!Can you share me the processed dataset?

Ok, give me your e-mail.

**Comment by sherlockers** [comment]
> > > Guys, the error disappeared after reducing the version of Pytorch(<= 1.4). @sherlockers @mercier111 @C-SunRay
> > 
> > 
> > Hi!Can you share me the processed dataset?
> 
> Ok, give me your e-mail.
wddygyhm@gmail.com. thanks!

**Comment by C-SunRay** [comment]
many thanks to you @whuyyc  although i don’t need that now lol.

**Comment by GANG370** [comment]
> 
Hi!Can you share me the processed dataset?2280137179@qq.com
Thanks!
